;; UTF-8
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-language-environment 'utf-8)
(set-selection-coding-system 'utf-8)

;; Display
(global-linum-mode)
(column-number-mode t)
(show-paren-mode t)
(global-hl-line-mode 1)
(setq frame-title-format "%b@yawl2u")

;; maximize frame on start-up
(add-to-list 'default-frame-alist '(fullscreen . maximized))

;; default font
(use-package cnfonts
  :ensure t
  :after all-the-icons
  :hook (cnfonts-set-font-finish
         . (lambda (fontsizes-list)
             (set-fontset-font t 'unicode (font-spec :family "all-the-icons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "file-icons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "Material Icons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "github-octicons") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "FontAwesome") nil 'append)
             (set-fontset-font t 'unicode (font-spec :family "Weather Icons") nil 'append)))
  :config
  (cnfonts-enable))

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(set-face-attribute
 'default nil
 :font (font-spec :name "-outline-Fira Code-normal-normal-normal-mono-*-*-*-*-c-*-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 12.5))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font
   (frame-parameter nil 'font)
   charset
   (font-spec :name "-outline-宋体-normal-normal-normal-*-*-*-*-*-p-*-iso10646-1"
              :weight 'normal
              :slant 'normal
              :size 15.5)))

;; Remove
(tool-bar-mode 0)
(menu-bar-mode 0)
(scroll-bar-mode 0)
(setq inhibit-startup-message t)
(setq gnus-inhibit-startup-message t)
(setq ring-bell-function 'ignore)

;; store all backup files
(setq backup-directory-alist '(("." . "~/.emacs.d/.saves")))
(setq make-backup-files t     ; backup of a file the first time it is saved.
      backup-by-copying t     ; dont clobber symlinks
      version-control t       ; version numbers for backup files
      delete-old-versions t   ; delete excess backup files silently
      delete-by-moving-to-trash t
      kept-old-versions 6     ; oldest versions to keep when a new numbered backup is made (default: 2)
      kept-new-versions 9
      auto-save-default t     ; auto-save every buffer that visits a file
      auto-save-timeout 20    ; number of seconds idle time before auto-save (default: 30)
      auto-save-interval 200  ; number of keystrokes between auto-saves (default: 300)
      )

;; the max delete recording
(setq kill-ring-max 200)

(fset 'yes-or-no-p 'y-or-n-p)
